name: Test Deploy and DAST

on: workflow_dispatch

jobs:

  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

     
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  test-dast:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: echo ${PWD} && ls -lR; cd ./ci/; docker-compose -f "docker-compose.yml" up -d --build

    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.6.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'owasp/zap2docker-stable'
        target: 'http://localhost:8000/soat-order-food/v1/health/actuator'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'        

    - name: Stop containers
      if: always()
      run: pwd; ls -la; cd ./ci/ ; docker-compose -f "docker-compose.yml" down
