name: Test Deploy and DAST

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: echo ${PWD} && ls -lR; cd ./ci/; docker-compose -f "docker-compose.yml" up -d --build

    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.6.0
      with:
        target: 'http://localhost:8000/soat-order-food/v1/health/actuator'
        cmd_options: -config ratelimit.rules.rule.enabled=true -config ratelimit.rules.rule.reqsPerSec=3 -config scanner.threadPerHost=1

    - name: Stop containers
      if: always()
      run: cd ./ci/ ; docker-compose -f "docker-compose.yml" down
