name: Test Deploy and DAST

on: workflow_dispatch

jobs:

  build:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: echo ${PWD} && ls -lR; cd ./ci/; docker-compose -f "docker-compose.yml" up -d --build

    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.6.0
      with:
        docker_name: 'owasp/zap2docker-stable'
        target: 'http://localhost:8000/soat-order-food/v1/health/actuator'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
     
        

    - name: Stop containers
      if: always()
      run: cd ./ci/ ; docker-compose -f "docker-compose.yml" down
