name: Demo-Food

on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: cd ./ci/; docker-compose -f "docker-compose-local.yml" up -d --build
